-- 코드를 작성해주세요
SELECT I.ID
FROM ECOLI_DATA AS O
JOIN (SELECT E.ID, C.PARENT_ID
    FROM ECOLI_DATA AS E
    JOIN ECOLI_DATA AS C ON E.PARENT_ID = C.ID) AS I
    ON I.PARENT_ID = O.ID
WHERE O.PARENT_ID IS NULL
ORDER BY I.ID
