SELECT P.ID, IFNULL(C.CNT, 0) AS CHILD_COUNT
FROM ECOLI_DATA AS P
LEFT JOIN (SELECT C.PARENT_ID, COUNT(*) AS CNT
      FROM ECOLI_DATA AS C
      WHERE C.PARENT_ID IS NOT NULL
      GROUP BY C.PARENT_ID) AS C ON C.PARENT_ID = P.ID
ORDER BY P.ID ASC     
