-- 코드를 입력하세요
SELECT *
FROM
(SELECT N.SALES_DATE, N.PRODUCT_ID, N.USER_ID, N.SALES_AMOUNT
FROM ONLINE_SALE AS N
WHERE N.SALES_DATE LIKE '2022-03%'

UNION ALL

SELECT F.SALES_DATE, F.PRODUCT_ID, NULL AS USER_ID, F.SALES_AMOUNT
FROM OFFLINE_SALE AS F
WHERE F.SALES_DATE LIKE '2022-03%'
) AS T

ORDER BY T.SALES_DATE, T.PRODUCT_ID, T.USER_ID