-- 코드를 입력하세요
SELECT CAR.CAR_ID, CAR.CAR_TYPE, FLOOR(CAR.DAILY_FEE*30*(1-(DISCOUNT.DISCOUNT_RATE)/100)) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
LEFT JOIN (SELECT CAR_TYPE, DURATION_TYPE, DISCOUNT_RATE
            FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
            WHERE DURATION_TYPE = '30일 이상') AS DISCOUNT ON DISCOUNT.CAR_TYPE = CAR.CAR_TYPE
WHERE (CAR.CAR_TYPE ='세단' OR CAR.CAR_TYPE='SUV')
    AND CAR.CAR_ID NOT IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE START_DATE <= '2022-11-30' AND END_DATE>='2022-11-01')
    AND (CAR.DAILY_FEE*30*(1-(DISCOUNT.DISCOUNT_RATE)/100) >=500000)
    AND (CAR.DAILY_FEE*30*(1-(DISCOUNT.DISCOUNT_RATE)/100) <2000000)    
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC