-- 코드를 작성해주세요

SELECT R.ID, CASE 
    WHEN R.RANK_GROUP = 1 THEN 'CRITICAL'
    WHEN R.RANK_GROUP = 2 THEN 'HIGH'
    WHEN R.RANK_GROUP = 3 THEN 'MEDIUM'
    ELSE 'LOW' END AS COLONY_NAME
FROM (SELECT ID, NTILE(4) OVER (ORDER BY SIZE_OF_COLONY DESC) AS RANK_GROUP
    FROM ECOLI_DATA) AS R
ORDER BY R.ID