WITH RECURSIVE GENERATION_INFO AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT E.ID, E.PARENT_ID, G.GENERATION + 1
    FROM ECOLI_DATA AS E
    JOIN GENERATION_INFO AS G ON E.PARENT_ID = G.ID
)
SELECT 
    COUNT(*) AS COUNT,
    GI.GENERATION
FROM GENERATION_INFO AS GI
LEFT JOIN ECOLI_DATA AS CHILD ON GI.ID = CHILD.PARENT_ID
WHERE CHILD.ID IS NULL  -- 자식이 없는 개체만
GROUP BY GI.GENERATION
ORDER BY GI.GENERATION