WITH TOTAL AS (
SELECT  F.SHIPMENT_ID, F.FLAVOR, F.TOTAL_ORDER
FROM FIRST_HALF AS F
    
    UNION ALL
SELECT J.SHIPMENT_ID, J.FLAVOR, J.TOTAL_ORDER
FROM JULY AS J
    
)

SELECT FLAVOR
FROM TOTAL
GROUP BY FLAVOR
ORDER BY SUM(TOTAL_ORDER) DESC
LIMIT 3
