SELECT D.ID, D.EMAIL, D.FIRST_NAME, D.LAST_NAME
FROM DEVELOPERS AS D
WHERE EXISTS (SELECT *
             FROM SKILLCODES AS S
             WHERE S.CODE & D.SKILL_CODE > 0 AND S.CATEGORY = 'Front End')
ORDER BY D.ID