SELECT 
    M.MEMBER_NAME,
    R.REVIEW_TEXT,
    DATE_FORMAT(R.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS R
JOIN MEMBER_PROFILE AS M 
    ON R.MEMBER_ID = M.MEMBER_ID
WHERE R.MEMBER_ID IN (
    SELECT MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    HAVING COUNT(*) = (
        SELECT MAX(A.TOTAL)
        FROM (
            SELECT COUNT(*) AS TOTAL
            FROM REST_REVIEW
            GROUP BY MEMBER_ID
        ) AS A
    )
)
ORDER BY R.REVIEW_DATE, R.REVIEW_TEXT;