-- 코드를 작성해주세요
SELECT B.ID, T.FISH_NAME, B.LENGTH
FROM FISH_INFO AS B
JOIN
(SELECT N.FISH_TYPE, N.FISH_NAME, MAX(I.LENGTH) AS MAX_LENGTH
FROM FISH_INFO AS I
JOIN FISH_NAME_INFO AS N ON I.FISH_TYPE = N.FISH_TYPE
GROUP BY I.FISH_TYPE) AS T
ON B.FISH_TYPE = T.FISH_TYPE
AND B.LENGTH = T.MAX_LENGTH