SELECT F.ID, T.FISH_NAME, F.LENGTH
FROM FISH_INFO AS F
JOIN(SELECT I.FISH_TYPE, I.FISH_NAME, M.LENGTH
     FROM FISH_NAME_INFO AS I
     JOIN (SELECT F.FISH_TYPE, MAX(F.LENGTH) AS LENGTH
           FROM FISH_INFO AS F
           GROUP BY F.FISH_TYPE) AS M ON I.FISH_TYPE = M.FISH_TYPE)AS T ON T.FISH_TYPE=F.FISH_TYPE
WHERE T.LENGTH = F.LENGTH
